# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieDatabase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieDatabase
  pod 'SDWebImage', '~> 5.0'

  target 'MovieDatabaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieDatabaseUITests' do
    # Pods for testing
  end

end
